---
- name: ZBX INSTALL SCRIPT
  hosts: decent-snake
  gather_facts: true
  tasks:
   - name: Copy file .deb
     become: yes
     ansible.builtin.copy:
       src: ./zbx/zabbix-agent_5.0.29-1+focal_amd64.deb
       dest: /home/zabbix-agent_5.0.29-1+focal_amd64.deb
       mode: '0644'
       
   - name: Install a .deb package
     ansible.builtin.apt:
       deb: /home/zabbix-agent_5.0.29-1+focal_amd64.deb
       
   - name: Copy file userparameters
     become: yes
     ansible.builtin.copy:
       src: ./zbx/userparameters
       dest: /etc/zabbix/zabbix_agentd.d/userparameters.conf
       mode: '0644'
       
   - name: Creates directory /var/lib/zabbix
     become: yes
     file:
       path: /var/lib/zabbix
       state: directory
       
   - name: Copy file psk.txt
     become: yes
     ansible.builtin.copy:
       src: ./zbx/psk.txt
       dest: /var/lib/zabbix/psk.txt
       mode: '0644'
       
   - name: Create zabbix-agentd.conf using Jinja2
     ansible.builtin.template:
       src: ./zbx/zabbix_template_ubuntu.j2 
       dest: /etc/zabbix/zabbix_agentd.d/zabbix-agentd.conf
       owner: bin
       mode: '0644'
       
   - name: Restart service 
     ansible.builtin.service:
       name: zabbix-agent
       state: restarted   
